apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owncloud-shared-pvc
  namespace: owncloud
spec:
  accessModes:
    - ReadWriteMany  # 여러 Pod이 동시 접근 가능
  storageClassName: nfs-client
  resources:
    requests:
      storage: 50Gi