apiVersion: v1
kind: Secret
metadata:
  name: owncloud-secret
  namespace: owncloud
type: Opaque
stringData:
  OWNCLOUD_ADMIN_USERNAME: "admin"
  OWNCLOUD_ADMIN_PASSWORD: "admin123!"
  OWNCLOUD_DB_USERNAME: "owncloud"
  OWNCLOUD_DB_PASSWORD: "owncloud123!"
  MYSQL_ROOT_PASSWORD: "root123!"